### PR TITLE
Fix/refactor project

### PR DESCRIPTION
**Pull request by Shawn-Armstrong**
Branch contains the same logic as the earlier prototype but organized using the prefered OpenTAP Python project setup.

### CODE REVIEW

**Comment by Shayan-Bathaee** [comment]
Comments on naming conventions for UR3e.py and MoveCobot.py:

Variable and function names should be snake_case/lower_with_under according to PEP8 style guide for python. See the following:
    - MoveCobot.py line 19 --> UR3e_cobot should be ur3e_cobot
    - MoveCobot.py line 22 --> Command should be command
    - MoveCobot.py line 31 --> Run should be run
    - UR3e.py line 8 --> IpAddress should be ip_address
    - UR3e.py line 60 --> Open should be open
    - UR3e.py line 64 --> Close should be close
    
According to [Google's naming style guide](https://google.github.io/styleguide/pyguide.html#s3.16-naming), it is also recommended to use CapWords for class names and lower_with_under for modules. Therefore, I think it might be a good idea to rename MoveCobot.py to move_cobot.py, and UR3e.py to ur3e.py.

**Comment by Shayan-Bathaee** [comment]
**SUMMARY:** Include .NET SDK as a requirement in the readme. In can be installed at [this link](https://aka.ms/dotnet-download).

**DETAIL:** First time I ran `dotnet build` as instructed in the the readme, I got an error relating to not having a .NET SDK. Here is the exact response:

```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

This response was fixed by going to the link and installing the .NET SDK on my machine. I went with version 7.0 and it worked fine.

**Comment by Shayan-Bathaee** [comment]
Additional instructions on configuring the UR3e for communication with OpenTAP might be a good idea, because following along with the GIF can be a little tedious. I would add the following above the GIF:

1. Click on the menu icon in the top right corner of the UR3e simulator, and click settings.
2. In the left menu, go to System > Network. Take note of the UR3e's IP address. 
3. In the OpenTAP editor, click the + icon to add a new test step. 
4. In the Pop-up test step window, select UR Prototype > Move Cobot > Add.
5. At the bottom of the window, right click the UR3e instrument, click Configure, and set the IP address as the IP address of the UR3e.
6. Click the green play button to run the test plan, and watch the UR3e move.

**Comment by Shayan-Bathaee** [comment]
I think the GIF for configuring the UR3e might be a little outdated. On my local machine, when I run `bin\tap editor`, the OpenTAP editor launches with the UR3e instrument already added. In the GIF, the user has to add the UR3e instrument manually. I tried running `tap editor` from the main OpenTAP directory, and it does not launch with the UR3e instrument, which makes me think that using `bin\tap editor` automatically adds it.

**Comment by Shayan-Bathaee** [comment]
There are instances of URe3 in the readme that should be changed to UR3e.

**Comment by Shawn-Armstrong** [comment]
Accidentally pushed it with a dummy account but that is me.

- Refactoring / Styling 
   1. [x] `MoveCobot.py` line 19 --> `UR3e_cobot` should be `ur3e_cobot`.
   2. [x] `MoveCobot.py` line 22 --> `Command` should be `command`.
   3. [ ] `MoveCobot.py`line 31 --> `Run` should be `run`.
      - This was generated via OpenTAP engine; I think it may be related to their existing hierarchy so I'm hesistant to change it. 
   4. [ ] `UR3e.py` line 60 --> `Open` should be `open`.
      - This was generated via OpenTAP engine; I think it may be related to their existing hierarchy so I'm hesistant to change it.
   5. [X] `UR3e.py` line 8 --> `IpAddress` should be `ip_address`.
   6. [ ] `UR3e.py` line 60 --> `Open` should be `open`.
      - This was generated via OpenTAP engine; I think it may be related to their existing hierarchy so I'm hesistant to change it.
   7. [ ] `UR3e.py` line 64 --> `Close` should be `close`.
      - This was generated via OpenTAP engine; I think it may be related to their existing hierarchy so I'm hesistant to change it.
- Technical Documentation
   1. [X] Update `README.md` requirements section to include .NET SDK.
   2. [X] Update `README.md` to include text explanation for longer gifs.
   3. [X] Update `README.md` GIF configuring UR3e.
   4. [X] Resolve `README.md` typos changing URe3 into UR3e.
   5. [X] Update `README.md` requirements section so that it uses the docker container setup. 
   6. [X] Update `README.md` instructions section to include docker setup. 
   7. [X] Update `README.md` usage section to include a more current example.

**Comment by Shayan-Bathaee** [comment]
Just looked it over, it runs great but one thing I noticed is that it might be helpful to add a little more detail about setting the UR3e instrument IP address. Under the bullet point that says "At the bottom of the window...", I think a sub-bullet that says:
- You can find this by running `ipconfig` in a windows terminal, and searching for your Wireless LAN adapter IPv4 Address.

would be really helpful.

**Pull request merged**
